"""add_outfit_history_and_item_usage_stats

Revision ID: 9e09157f30a7
Revises: 46c2d23dd769
Create Date: 2025-11-19 02:47:49.531706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e09157f30a7'
down_revision: Union[str, None] = '46c2d23dd769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outfit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('occasion', sa.String(), nullable=True),
    sa.Column('item_ids', sa.Text(), nullable=True),
    sa.Column('outfit_name', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('shown_at', sa.DateTime(), nullable=True),
    sa.Column('was_favorited', sa.Integer(), nullable=True),
    sa.Column('was_dismissed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_history_id'), 'outfit_history', ['id'], unique=False)
    op.create_index(op.f('ix_outfit_history_shown_at'), 'outfit_history', ['shown_at'], unique=False)
    op.create_index(op.f('ix_outfit_history_user_id'), 'outfit_history', ['user_id'], unique=False)
    op.create_table('item_usage_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('total_shown', sa.Integer(), nullable=True),
    sa.Column('total_favorited', sa.Integer(), nullable=True),
    sa.Column('last_shown_at', sa.DateTime(), nullable=True),
    sa.Column('first_shown_at', sa.DateTime(), nullable=True),
    sa.Column('occasion_counts', sa.Text(), nullable=True),
    sa.Column('validation_failures', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('versatility_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['clothing_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_usage_stats_id'), 'item_usage_stats', ['id'], unique=False)
    op.create_index(op.f('ix_item_usage_stats_item_id'), 'item_usage_stats', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_usage_stats_user_id'), 'item_usage_stats', ['user_id'], unique=False)
    # Note: SQLite doesn't support ALTER COLUMN, skipping type changes for brand/model/last_shown
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_usage_stats_user_id'), table_name='item_usage_stats')
    op.drop_index(op.f('ix_item_usage_stats_item_id'), table_name='item_usage_stats')
    op.drop_index(op.f('ix_item_usage_stats_id'), table_name='item_usage_stats')
    op.drop_table('item_usage_stats')
    op.drop_index(op.f('ix_outfit_history_user_id'), table_name='outfit_history')
    op.drop_index(op.f('ix_outfit_history_shown_at'), table_name='outfit_history')
    op.drop_index(op.f('ix_outfit_history_id'), table_name='outfit_history')
    op.drop_table('outfit_history')
    # ### end Alembic commands ###
